name :  Generate ASII Framework

on:
    push

jobs:
    build_job_1:
        runs-on : ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y
        
        - name : Execute cowsay CMD
          run : cowsay -f dragon "Run for cover, I am a DRAGON ... RWAR" >> dragon.txt

        - name : Upload dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: my-artifact
            path: dragon.txt
    
    build_job_2:
        needs: build_job_1 
        runs-on : ubuntu-latest
        steps:
        - name : Upload dragon text file
          uses: actions/download-artifact@v4
          with:
            name: my-artifact
        
        - name : Test File exists
          run : grep -i "dragon" dragon.txt


    build_job_3:
        needs: [build_job_2]
        runs-on : ubuntu-latest
        steps:
        - name : Upload dragon text file
          uses: actions/download-artifact@v4
          with:
            name: my-artifact
            
        - name : Read File
          run: cat dragon.txt

        - name : Deploy
          run: echo Deploying ....
        

