name :  Generate ASII Framework

on:
    push

jobs:
    build_job_1:
        runs-on : ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name : List All Projects
          run : ls -ltra

        - name : Executing Schell Script
          run : |
            chmod +x asii-script.sh
            ./asii-script.sh
    
    build_job_2:
        runs-on : ubuntu-latest
        steps:
        - name: Sleep for 10s
          uses: sleep 10
        
        - name : Test File exists
          run : grep -i "dragon" dragon.txt


    build_job_3:
        runs-on : ubuntu-latest
        steps:
        - name : Read File
          run: cat dragon.txt

        - name : Deploy
          run: echo Deploying ....
        

