name :  Generate ASII Framework

on:
    push

jobs:
    asii_job:
        runs-on : ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name : List All Projects
          run : ls -ltra

        - name : Executing Schell Script
          run : |
            chmod +x aasii-script.sh
            ./asii-script.sh
        
        

